-- Database: albums

-- DROP DATABASE IF EXISTS albums;

CREATE TABLE ARTISTS(
	ID INT PRIMARY KEY,
	NAME VARCHAR(15)
);

CREATE TABLE ALBUMS(
	ID INT PRIMARY KEY,
	RELYEAR INT,
	TITLE VARCHAR(10)
);

CREATE TABLE GENRES(
	ID INT PRIMARY KEY,
	NAME VARCHAR(5)
);

CREATE TABLE ASSOC(
	ARTIST_ID INT,
	ALBUM_ID INT,
	GENRE_ID INT
);

ALTER TABLE ASSOC
ADD CONSTRAINT FK_ARTIST
FOREIGN KEY(ARTIST_ID) REFERENCES ARTISTS (ID);
ALTER TABLE ASSOC
ADD CONSTRAINT FK_ALBUM
FOREIGN KEY(ALBUM_ID) REFERENCES ALBUMS (ID);
ALTER TABLE ASSOC
ADD CONSTRAINT FK_GENRE
FOREIGN KEY(GENRE_ID) REFERENCES GENRES (ID);